### ISSUE TITLE
key entered are not getting displayed

### ISSUE THREAD

**Issue by jayshetti** [kshoji/BLE-HID-Peripheral-for-Android#3]
I am able to connect my android device as input device via bluetooth also my connected device interpret it as keyboard but when i send key from my device it is not getting displayed.

**Comment by tejado** [comment]
Hi,

why closed? Did it work for you? What devices are you using?
Thanks :)

**Comment by jayshetti** [comment]
Hi,

Sometimes i am facing that issue sometimes it is working fine for me.
I am using android device.

**Comment by shinil7** [comment]
Does this issue happen when you connect the mouse first and switch to keyboard after that?

**Comment by zhubinsheng** [comment]
how to fix this problem
